### PR TITLE
[Helm] Added paths value in values.yaml and Service type templating.

### PR DESCRIPTION
**Pull request by diegonayalazo**
Needed when creating an ingress an missing in the example values.yaml.

Thanks for the project!
Regards,

Diego

### CODE REVIEW

**Comment by ibrahimkk-moideen** [comment]
@diegonayalazo Could you sign the CLA when you get a chance.

**Comment by diegonayalazo** [comment]
Hi @ibrahimkk-moideen  , even though I signed it, it appears unsigned, is there a way to reset it?
image

**Comment by diegonayalazo** [comment]
Thanks I will start from scratch. Thanks for the email obfucastion. Would you mind deleting my whole email address even if scrubbed? Much appreciated

**Comment by derrick-dacosta** [comment]
Thank you and done!

**Pull request closed without merging**
